### ISSUE TITLE
[QUESTION]关于源码中的 {{{ruby(xxx,xxx)}}}

### ISSUE THREAD

**Issue by nasyxx** [jcouyang/blog#5]
（很抱歉有点离题，但是没找到其他方式询问）
见到乃的博客中在一些中文上方以这种方式标示了英文，就很好奇，这个是怎么实现的，于是就追到了这儿。但是，我发现我依然无法搞清楚。

请问，这是一个 org 的插件吗？还是什么让它生成这样的？

**Comment by jcouyang** [comment]
https://raw.githubusercontent.com/jcouyang/blog/master/org/grokking-monad/part1.org

第五行 `#+MACRO: ruby @@html:<ruby>$1<rt>$2</rt></ruby>@@`

是 org 的 macro 把`{{{ruby()}}}` 变 `<ruby>$1<rt>$2</rt></ruby>`

`<ruby>` 是 html的tag

**Comment by nasyxx** [comment]
原来如此，非常感谢！
