### ISSUE TITLE
Is there any other steps to do for deploy site on netlify?

### ISSUE THREAD

**Issue by oit63** [jcouyang/blog#8]
I just tried netlify 
but I met a failure.

**Comment by oit63** [comment]
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/pratical Monads.html using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/images/functional-ruby-qr.jpg using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/images/functional-ruby-qr.gif using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/fprb.html using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/high-performance-ui.html using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/essential-ecmascript-2017.html using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/continuous-delivery.html using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/slides/functional-ruby.html using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/favicon.ico using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/f.ico using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/style/toc.css using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/style/gh-fork-ribbon.ie.css using ‘org-publish-attachment’
12:06:08 AM: Publishing file /opt/build/repo/assets/style/worg.css using ‘org-publish-attachment’
12:06:09 AM: Error running command: Build script returned non-zero exit code: 1
12:06:09 AM: Failing build: Failed to build site
12:06:09 AM: failed during stage 'building site': Build script returned non-zero exit code: 1

**Comment by oit63** [comment]
Could you please give some advice?

**Comment by jcouyang** [comment]
I'm having the same issue with netlify build sometimes as well, usually a retry will solve it

**Comment by oit63** [comment]
You are right.
I clear cache and build again, work!
